### ISSUE TITLE
What should our project be based on?

### ISSUE THREAD

**Issue by GaryMcHugh** [Smurfffy/EmergingTechProject#1]
we need to come up with an idea for what our project will be about.

**Comment by DarrenFitz** [comment]
How about something like a webpage for a hospital? Use database for Doctors, patients etc.

**Comment by JasonMcTigue** [comment]
Maybe a library webpage so we could search for books and sort them into categories and have a login for users where we store there usernames and passwords in a database?

**Comment by Smurfffy** [comment]
I think we can all agree on the library webpage. Ian told Gary we can use a template for the webpage so we should all look through bootstrap for ideas.
