### ISSUE TITLE
I solved the jquery not working in chrome issue

### ISSUE THREAD

**Issue by GaryMcHugh** [Smurfffy/EmergingTechProject#16]
The following steps will fix the issue:

1. open a command prompt
2. cd to the directory with chrome.exe, it was (C:\Program Files (x86)\Google\Chrome\Application) for me
3. run the following command: .\chrome.exe --allow-file-access-from-files
4. restart all instances of chrome
5. run the html file that uses jquery and it will work!

**Comment by GaryMcHugh** [comment]
The only issue is you will have to do this every time you restart your computer.... so I suggest we just use Firefox

**Comment by GaryMcHugh** [comment]
http://stackoverflow.com/questions/10752055/cross-origin-requests-are-only-supported-for-http-error-when-loading-a-local

That link explains what the issue is (we are running the jquery from our file system and not a web server)

**Comment by JasonMcTigue** [comment]
Yeah that makes a lot more sense now.
