### ISSUE TITLE
Getting index.html to run at the root by default

### ISSUE THREAD

**Issue by GaryMcHugh** [Smurfffy/EmergingTechProject#3]
Does anyone have any links to help me to get index.html to run by default?

**Comment by JasonMcTigue** [comment]
[Writing Web Applications](https://golang.org/doc/articles/wiki/) Found this thought it would be useful for everyone to have a look at.

**Comment by DarrenFitz** [comment]
put index.html in the public folder to make it run root by default. Ian has an example on his github https://github.com/emerging-technologies/example-webapp
