### ISSUE TITLE
Other pages

### ISSUE THREAD

**Issue by GaryMcHugh** [Smurfffy/EmergingTechProject#5]
We need to work on the other pages in the website, I think we should delegate the task so a person takes a page each, what do ye think?

**Comment by JasonMcTigue** [comment]
Yeah that's defiantly a good idea!

**Comment by Smurfffy** [comment]
I'll take care of the opening hours page

**Comment by DarrenFitz** [comment]
Okay i'll do contact us!

**Comment by JasonMcTigue** [comment]
Cool Ill do the about us page then.

**Comment by GaryMcHugh** [comment]
sweet, I'll do the home page
