### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by GaryMcHugh** [Smurfffy/EmergingTechProject#6]
Does anyone have any ideas for what we could put on the bottom parts of the home page? I've added an image to show what section I am talking about.
![image](https://cloud.githubusercontent.com/assets/9326229/19985662/977ec336-a20b-11e6-9145-c82dc50a591b.png)

**Comment by JasonMcTigue** [comment]
I was thinking we could maybe add something like this and maybe link to the gmit Twitter and Facebook pages? Not sure if that would really suit our webpage though.

![footer](https://cloud.githubusercontent.com/assets/10633268/20040331/0184c472-a44d-11e6-8e8f-ef13fa2689a6.PNG)

**Comment by GaryMcHugh** [comment]
Yeah The social media links sound like a good idea to me! Where in the website would we put them though?
